# Generated by Django 5.2.12 on 2026-04-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_created_at_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.traineravailability'),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.CharField(blank=True, choices=[('baseball', 'Baseball'), ('softball', 'Softball'), ('football', 'Football'), ('basketball', 'Basketball'), ('track_field', 'Track & Field'), ('cross_country', 'Cross Country'), ('soccer', 'Soccer'), ('bowling', 'Bowling'), ('golf', 'Golf'), ('lacrosse', 'Lacrosse'), ('cheerleading', 'Cheerleading'), ('volleyball', 'Volleyball')], max_length=25),
        ),
    ]
