# Generated by Django 5.2.12 on 2026-04-21 03:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_availability_user_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[main.models.validate_madonna_email]),
        ),
    ]
