# Generated by Django 5.2.12 on 2026-04-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='microsoft_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('trainer', 'Trainer')], default='athlete', max_length=20),
        ),
    ]
